# -*- coding: utf-8 -*-
"""Codes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_5WifUcItVeVtAFfOin1cW1CVaSa8ED

Classification
"""

# Importing numpy and pandas for data manipulation and performing calculation
import numpy as np
import pandas as pd

# Importing dataset
data = pd.read_csv('/content/Accidental_Drug_Related_Deaths.csv')
data

# Display number of row and attributes
data.shape

# Display information for each attribute
data.info()

# Display display sum of empty value for each attribute
data.isnull().sum()

"""Data Preprocessing"""

# Drop irrelevant data attribute or not do present must meaningful result
data.drop(['Other Significant Conditions ', 'Ethnicity', 'Location if Other', 'Heroin death certificate (DC)',
           'Heroin/Morph/Codeine', 'Manner of Death', 'Date Type', 'Other'], axis=1, inplace=True)

# Replace values other than 'Male' and 'Female' with an empty string
data.loc[~data['Sex'].isin(['Male', 'Female']), 'Sex'] = ''

# Calculate the mode while excluding the empty string
mode = data['Sex'][data['Sex'] != ''].mode()[0]

# Fill empty values with the calculated mode
data['Sex'] = data['Sex'].replace('', mode)

# Print the unique values
print(data['Sex'].unique())

# Make all result Black or African American into Black
data.loc[data['Race'].isin(['Black', 'Black or African American']), 'Race'] = 'Black'

# Make all other result into other except for Black and White
data.loc[~data['Race'].isin(['Black', 'White']), 'Race'] = 'Other'

# This is to generlise the race group

# Filling all empty result in attribute 'Age' with median values
data['Age'] = data['Age'].fillna(data['Age'].median())

# Initializing a list of drugs
drugs = ['Heroin', 'Cocaine', 'Fentanyl', 'Oxycodone', 'Oxymorphone', 'Ethanol', 'Hydrocodone',
         'Benzodiazepine', 'Methadone', 'Amphet', 'Tramad', 'Meth/Amphetamine',
         'Morphine (Not Heroin)', 'Hydromorphone', 'Fentanyl Analogue',
         'Xylazine', 'Gabapentin', 'Opiate NOS', 'Other Opioid', 'Any Opioid']

# Filling all missing values in drugs
for drug in drugs:
    data[drug] = data[drug].fillna('N')

# Print result for 'Cocaine'
data['Cocaine']

# For all drug in variable 'drugs', print all unique value for each drugs
for drug in drugs:
   unique_values = data[drug].unique()
   print(f"Unique values for '{drug}': {unique_values}")

# Replacing unique value into only 'Y' or 'N'

for drug in drugs:
    # Replace 'y' with 'Y', for proper generalising the results
    data[drug] = data[drug].replace('y', 'Y')

    # Replace values expect for 'Other Opioid' that is not 'Y' or 'N' with 'N'
    if drug != 'Other Opioid':
        data.loc[~data[drug].isin(['Y', 'N']), drug] = 'N'

    # Replace value for 'Other Opioid' that is not 'Y' or 'N' with 'Y'
    if drug == 'Other Opioid':
        data.loc[~data[drug].isin(['Y', 'N']), drug] = 'Y'

# Print result for each drug to verify its unique values again
for drug in drugs:
   unique_values = data[drug].unique()
   print(f"Unique values for '{drug}': {unique_values}")

# Fill in any remaining missing value with median or mode

for col in data.columns:
    if data[col].isnull().any():
        if data[col].dtype == 'object':
            data[col] = data[col].fillna(data[col].mode()[0])
        else:
            data[col] = data[col].fillna(data[col].median())

data.isnull().sum()

# Check for duplicated rows and remove
duplicate_rows = data[data.duplicated()]
print("Duplicated Rows:")
print(duplicate_rows)

data_no_duplicates = data.drop_duplicates()
print("\nDataframe after removing duplicates:")

# Extract lantitude and longitude from these attribute for its numerical attribute, as they were part of categorical attribute
import re
def extract_lat_lon(geo_column):
    latitudes = []
    longitudes = []

    for value in geo_column:
        match = re.search(r"\(([-\d.]+), ([-\d.]+)\)", str(value))
        if match:
            latitudes.append(float(match.group(1)))
            longitudes.append(float(match.group(2)))
        else:
            latitudes.append(None)
            longitudes.append(None)

    return latitudes, longitudes


data["Residence City_Latitude"], data["Residence City_Longitude"] = extract_lat_lon(data["ResidenceCityGeo"])
data["Injury City_Latitude"], data["Injury City_Longitude"] = extract_lat_lon(data["InjuryCityGeo"])
data["Death City_Latitude"], data["Death City_Longitude"] = extract_lat_lon(data["DeathCityGeo"])

# Dropping these attribute as they are already present
data.drop(columns=["ResidenceCityGeo", "InjuryCityGeo", "DeathCityGeo"], inplace=True)

# Reorder the longitude and latitude attribute to associate with respective attributes
column_order = []
for col in data.columns:
    if col == "Residence City":
        column_order.extend([col, "Residence City_Latitude", "Residence City_Longitude"])
    elif col == "Injury City":
        column_order.extend([col, "Injury City_Latitude", "Injury City_Longitude"])
    elif col == "Death City":
        column_order.extend([col, "Death City_Latitude", "Death City_Longitude"])
    elif col not in ["Residence City_Latitude", "Residence City_Longitude",
                     "Injury City_Latitude", "Injury City_Longitude",
                     "Death City_Latitude", "Death City_Longitude"]:
        column_order.append(col)

data = data[column_order]
data

# Convert drugs into proper naming format
data = data.rename(columns={'Morphine (Not Heroin)': 'Morphine'})

drugs = ['Heroin', 'Cocaine', 'Fentanyl', 'Oxycodone', 'Oxymorphone', 'Ethanol', 'Hydrocodone', 'Benzodiazepine', 'Methadone', 'Amphet', 'Tramad',
         'Morphine', 'Hydromorphone', 'Fentanyl Analogue', 'Meth/Amphetamine', 'Xylazine', 'Gabapentin', 'Opiate NOS', 'Other Opioid', 'Any Opioid']

# For the list of drugs, perform encoding to convert 'Y' to 1 and 'N' into 0, this allows to display result in numerical format
for col in  ['Heroin', 'Cocaine', 'Fentanyl', 'Oxycodone', 'Oxymorphone', 'Ethanol', 'Hydrocodone', 'Benzodiazepine', 'Methadone', 'Amphet', 'Tramad',
         'Morphine', 'Hydromorphone', 'Fentanyl Analogue', 'Meth/Amphetamine', 'Xylazine', 'Gabapentin', 'Opiate NOS', 'Other Opioid', 'Any Opioid']:
             data[col] = data[col].replace({'Y': 1, 'N': 0})

"""Train-Test Split"""

# Perform categorical encoding for attribute 'Sex' and 'Race'
data = pd.get_dummies(data, columns=['Sex', 'Race'])

# Feature Selection to select attribute to perform classifcation task
features = ["Age", "Residence City_Latitude", "Residence City_Longitude", "Sex_Female", "Sex_Male", "Race_White", "Race_Black", "Race_Other"]
X = data[features]
y = data["Any Opioid"]

# Importing libraries to perform classification tast
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# ColumnTransformer allow selected attribute to be preprocess, while keeping other attribute not affected
# StandardScaler allow scaling numerical result into between 0 and 1, this allow no attribute of result in dominating the analysis
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), ["Age", "Residence City_Latitude", "Residence City_Longitude"]),
    ("cat", "passthrough", ["Sex_Female", "Sex_Male", "Race_White", "Race_Black", "Race_Other"])
])

# Performing train-test split with 80/20 splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

"""Performing Classification with Different Algorithm and Evaluation Metrics"""

# Importing different classification algorithm to perform classificatin task
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB

# Importing evaluation metric to measure performance for each different classfication algorithm
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, f1_score

# Firstly for Random Forest Algorithm
print("\nTraining Random Forest")

# Pipeline ensure no data leakage occurs
# Classifier is set parameter to perform random forest algorithm
rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(n_estimators=100, random_state=42))
])

# Feature are split into training and testing after preprocessing
rf_pipeline.fit(X_train, y_train)
y_pred = rf_pipeline.predict(X_test)

# Print performance metric score for Random Forest Algorithms
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-score:", f1_score(y_test, y_pred))
print("")
print(classification_report(y_test, y_pred))

rf_accuracy = accuracy_score(y_test, y_pred)
print(f"Random Forest Accuracy: {rf_accuracy}")

# Second for K-Nearest Neighbors algorithms
print("\nTraining K-Nearest Neighbors")

# Pipeline ensure no data leakage occurs
# Classifier is set parameter to perform K-Nearest Neighbors algorithm
knn_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", KNeighborsClassifier(n_neighbors=5))
])

# Feature are split into training and testing after preprocessing
knn_pipeline.fit(X_train, y_train)
y_pred = knn_pipeline.predict(X_test)

# Print performance metric score for Random Forest Algorithms
print("KNN Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-score:", f1_score(y_test, y_pred))
print("")
print(classification_report(y_test, y_pred))

KNN_accuracy = accuracy_score(y_test, y_pred)
print(f"K-Nearest Neightbors Accuracy: {KNN_accuracy}")

# Third for Artificial Neural Network algorithms
print("\nTraining Artificial Neural Network")

# Pipeline ensure no data leakage occurs
# Classifier is set parameter to perform Artificial Neural Network algorithms
ann_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", MLPClassifier(hidden_layer_sizes=(64, 32), activation='relu', solver='adam'
    , max_iter=500, random_state=42))
])

# Feature are split into training and testing after preprocessing
ann_pipeline.fit(X_train, y_train)
y_pred = ann_pipeline.predict(X_test)

# Print performance metric score for Artificial Neural Network algorithms
print("ANN Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-score:", f1_score(y_test, y_pred))
print("")
print(classification_report(y_test, y_pred))

ANN_accuracy = accuracy_score(y_test, y_pred)
print(f"Artificial Neural Network Accuracy: {ANN_accuracy}")

# Four for Naive Bayes algorithms
print("\nTraining Naive Bayes")

# Pipeline ensure no data leakage occurs
# Classifier is set parameter to perform Naive Bayes algorithms
nb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", GaussianNB())
])

# Feature are split into training and testing after preprocessing
nb_pipeline.fit(X_train, y_train)
y_pred = nb_pipeline.predict(X_test)

# Print performance metric score for Naive Bayes algorithms
print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-score:", f1_score(y_test, y_pred))
print("")
print(classification_report(y_test, y_pred))

NB_accuracy = accuracy_score(y_test, y_pred)
print(f"Naive Bayes Accuracy: {NB_accuracy}")

"""Cross Validation"""

# Import libraries to perform and evaluate cross-validation for using k-fold
from sklearn.model_selection import cross_val_score, KFold

# Initialize models with pipelines represent different alogrithms
models = {
    "Random Forest": rf_pipeline,
    "K-Nearest Neighbors": knn_pipeline,
    "Artificial Neural Network": ann_pipeline,
    "Naive Bayes": nb_pipeline
}

# Parameters to perform cross validation using K-fold method
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation for each model
cv_results = {}

# Cross validation will only perform and evaluate using 'accuracy_score'
for name, pipeline in models.items():
    scores = cross_val_score(pipeline, X_train, y_train, cv=kf, scoring='accuracy')

    # Perform mean and standard deviation calculation for accuracy score using K-fold
    mean_accuracy = scores.mean()
    std_dev = scores.std()

    cv_results[name] = mean_accuracy
    print(f"{name}: Mean Accuracy = {mean_accuracy:.4f}, Std Dev = {std_dev:.4f}")

# Store cross-validation results
cv_accuracy_scores = cv_results

# Import libraries to perform and evaluate cross-validation for using stratified K-fold
from sklearn.model_selection import StratifiedKFold, cross_val_score

# Parameters to perform cross validation using Stratified K-fold method
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation for each model
cv_results_stratified = {}

# Cross validation will only perform and evaluate using 'accuracy_score'
for name, pipeline in models.items():
    scores = cross_val_score(pipeline, X_train, y_train, cv=skf, scoring='accuracy')

    # Perform mean and standard deviation calculation for accuracy score using K-fold
    mean_accuracy = scores.mean()
    std_dev = scores.std()

    cv_results_stratified[name] = mean_accuracy  # Save mean accuracy
    print(f"{name} (Stratified CV): Mean Accuracy = {mean_accuracy:.4f}, Std Dev = {std_dev:.4f}")

# Store cross-validation results
cv_accuracy_scores_stratified = cv_results_stratified

"""Data Visualisation"""

# Import libraries for data visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Storing each accuracy score for each model in a dictionary called 'test_accuracies'
test_accuracies = {
    "Random Forest": rf_accuracy,
    "K-Nearest Neighbors": KNN_accuracy,
    "Artificial Neural Network": ANN_accuracy,
    "Naive Bayes": NB_accuracy
}

# Cross validation accuracy score is assign into variable 'accuracies'
cv_accuracies = cv_accuracy_scores

# Convert into data frame to perform data visualisation
accuracy_df = pd.DataFrame({
    "Model": test_accuracies.keys(),
    "Test Accuracy": test_accuracies.values(),
    "Cross-Validation Accuracy": cv_accuracies.values()
})

# Perform melt to allow easier to perform data visualisation and displaying result
accuracy_df = accuracy_df.melt(id_vars=["Model"], var_name="Metric", value_name="Accuracy")

# Display result after melt process
print(accuracy_df)

# Plot visualisation for comparison for Test Accuracy and Cross validation accuracy
plt.figure(figsize=(10, 6))

# Plot X with Models name and Y for accuracy result
sns.barplot(x="Model", y="Accuracy", hue="Metric", data=accuracy_df, palette="coolwarm")

# Set Limits into between 0 to 1
plt.ylim(0, 1)
plt.title("Test Accuracy vs. Cross-Validation Accuracy")
plt.xlabel("Model")
plt.ylabel("Accuracy Score")
plt.legend(title="Metric")
plt.show()

# Convert dictionary to lists for plotting
model_names = list(test_accuracies.keys())
accuracies = list(test_accuracies.values())

# Parameter for plot
plt.figure(figsize=(8, 5))
sns.barplot(x=accuracies, y=model_names, palette="coolwarm")

# Labels and title
plt.xlabel("Accuracy Score")
plt.ylabel("Model")
plt.title("Model Accuracy Comparison")
plt.xlim(0, 1)

# Show the plot
plt.show()

# Convert results into lists
models_list = list(cv_accuracy_scores.keys())

kfold_means = [cv_accuracy_scores[model] for model in models_list]
kfold_stds = [np.std(cross_val_score(models[model], X_train, y_train, cv=kf)) for model in models_list]

stratified_means = [cv_accuracy_scores_stratified[model] for model in models_list]
stratified_stds = [np.std(cross_val_score(models[model], X_train, y_train, cv=skf)) for model in models_list]

# Bar width and x locations
bar_width = 0.35
x = np.arange(len(models_list))

# Create bar plot
fig, ax = plt.subplots(figsize=(10, 6))

# Accuracy bars
ax.bar(x - bar_width/2, kfold_means, bar_width, label="K-Fold Accuracy", color="royalblue")
ax.bar(x + bar_width/2, stratified_means, bar_width, label="Stratified K-Fold Accuracy", color="lightseagreen")

# Standard deviation bars (error bars)
ax.errorbar(x - bar_width/2, kfold_means, yerr=kfold_stds, fmt="o", color="black", capsize=5, label="K-Fold Std Dev")
ax.errorbar(x + bar_width/2, stratified_means, yerr=stratified_stds, fmt="o", color="red", capsize=5, label="Stratified K-Fold Std Dev")

# Labels & formatting
ax.set_xlabel("Models")
ax.set_ylabel("Accuracy Score")
ax.set_title("Comparison of Accuracy & Standard Deviation (K-Fold vs Stratified K-Fold)")
ax.set_xticks(x)
ax.set_xticklabels(models_list, rotation=20)
ax.set_ylim(0, 1)  # Set limit between 0 and 1 for accuracy
ax.legend()

plt.show()

# Import Libraries for Precision_recall_curve
from sklearn.metrics import precision_recall_curve

plt.figure(figsize=(8, 6))

for name, model in models.items():
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    precision, recall, _ = precision_recall_curve(y_test, y_pred_proba)
    plt.plot(recall, precision, label=name)

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.legend()
plt.show()

# Import libraries for ROC curve
from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(8, 6))

for name, model in models.items():
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{name} (AUC = {roc_auc:.2f})")

# Plot ROC curve
plt.plot([0, 1], [0, 1], linestyle="--", color="gray")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Receiver Operating Characteristic (ROC) Curve")
plt.legend()
plt.show()